test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

development:
  adapter: postgresql
  encoding: unicode
  database: chippa_development
  pool: 5
  username: postgres
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: chippa_staging
  pool: 5
  username: deploy
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: chippa
  pool: 5
  username: deploy
  password:
